# RobotEnv runtime configuration
ENV_MAX_FORWARD_SPEED = 0.012   # максимальная скорость вперёд за один шаг среды
ENV_ACCELERATION = 0.002        # ускорение при нажатии на газ
ENV_FRICTION = 0.1              # торможение, если не нажат газ
ENV_BRAKE_STRENGTH = 0.25       # Насколько сильно тормоз снижает скорость
ENV_MAX_TURN_RATE = 0.08        # Максимальная скорость поворота за один шаг среды
ENV_STEERING_SMOOTHING_FACTOR = 0.25  # Насколько сглаживается поворот руля за один шаг среды
EPISODE_MAX_STEPS = 500
ENV_NUM_OBSTACLES = 4
ENV_ROBOT_RADIUS = 0.02
ENV_TARGET_RADIUS = 0.03

# Random generation and ray-casting settings
RAYS_AMOUNT_GENERATION = 12
MIN_FROM_ROBOT_TO_TARGET_DIST_GENERATION = 0.3
MIN_FROM_ROBOT_TO_OBS_DIST_GENERATION = 0.01
MIN_OBS_RADIUS_GENERATION = 0.05
MAX_OBS_RADIUS_GENERATION = 0.1
MAX_ATTEMPTS_FOR_WHILE_GENERATION = 100000
MIN_FROM_OBS_TO_OBS_DIST_GENERATION = 0.01
MIN_FROM_OBS_TO_TARGET_DIST_GENERATION = 0.02
MAP_EDGES_BUFFER_DURING_OBS_GENERATION = ENV_ROBOT_RADIUS * 2
MAP_EDGES_BUFFER_DURING_ROBOT_GENERATION = ENV_ROBOT_RADIUS * 2
MAP_EDGES_BUFFER_DURING_TARGET_GENERATION = 0.01

# Episode termination thresholds and ray normalization
FROM_ROBOT_TO_TARGET_DIST_ACCURACY_REGISTRATION = 0.001
FROM_ROBOT_TO_OBS_DIST_ACCURACY_REGISTRATION = 0.001
FROM_ROBOT_TO_EDGES_DIST_ACCURACY_REGISTRATION = 0.001
RAY_MAX_DIST = 2**0.5

# Reward shaping constants
DENSE_REWARD_COEFF = 200
TIME_PENALTY = 0.07
MIN_RAY_DISTANCE_TO_SAFE_ZONE_REGISTRATION = ENV_ROBOT_RADIUS * 7
PROXIMITY_PENALTY_COEFF = 0.7
OBSTACLE_APPROACH_PENALTY_COEFF = 0.7
LARGE_REWARD = 300
LARGE_PENALTY = 150
TIMEOUT_PENALTY = 20
MIN_MOVING_SPEED = 0.001
STAND_STILL_PENALTY = 0.05

# Training loop hyperparameters
TRAIN_NUM_EPISODES = 3000
TRAIN_AGENT_HIDDEN_SIZE = 256
TRAIN_LEARNING_RATE = 0.0001
TRAIN_GAMMA = 0.99
TRAIN_BUFFER_SIZE = 100000
TRAIN_BATCH_SIZE = 256
TRAIN_TARGET_UPDATE = 2000
TRAIN_MAX_GRAD_NORM = 8
TRAIN_EPSILON = 0.5
TRAIN_EPSILON_MIN = 0.07
TRAIN_EPSILON_DECAY = (TRAIN_EPSILON_MIN / TRAIN_EPSILON) ** (1 / (TRAIN_NUM_EPISODES - 200))
TRAIN_SUCCESS_RATE_WINDOW = 100


# Output paths and filenames
MODEL_DIR = "models"
DQN_MODEL_FILENAME = "DQN_discrete_control_model.pth"
DQN_LAST_MODEL_FILENAME = "last_DQN_discrete_control_model.pth"
TRAINING_RESULTS_FILENAME = "Training_results.png"

# Training progress and plot settings
TRAINING_PROGRESS_DESC = "Training"
TRAINING_PLOT_FIGSIZE = (12, 10)
TRAINING_PLOT_REWARD_SUBPLOT = (2, 2, 1)
TRAINING_PLOT_LOSS_SUBPLOT = (2, 2, 2)
TRAINING_PLOT_SUCCESS_RATE_SUBPLOT = (2, 2, 3)
TRAINING_PLOT_LENGTH_SUBPLOT = (2, 2, 4)
TRAINING_PLOT_REWARD_COLOR = "blue"
TRAINING_PLOT_LOSS_COLOR = "orange"
TRAINING_PLOT_SUCCESS_RATE_COLOR = "red"
TRAINING_PLOT_LENGTH_COLOR = "green"
TRAINING_PLOT_REWARD_TITLE = "Reward History"
TRAINING_PLOT_LOSS_TITLE = "Loss History"
TRAINING_PLOT_SUCCESS_RATE_TITLE = "Success Rate History"
TRAINING_PLOT_LENGTH_TITLE = "Episode Length History"
TRAINING_PLOT_EPISODE_LABEL = "Episode"
TRAINING_PLOT_REWARD_LABEL = "Reward"
TRAINING_PLOT_LOSS_LABEL = "Loss"
TRAINING_PLOT_SUCCESS_RATE_LABEL = "Success Rate"
TRAINING_PLOT_LENGTH_LABEL = "Episode Length"

# Discrete action ids and display names
ACTION_THROTTLE_LEVELS = (0.0, 0.5, 1.0)
ACTION_STEERING_LEVELS = (-1.0, -0.5, 0.0, 0.5, 1.0)
DISCRETE_ACTIONS = []
for throttle in ACTION_THROTTLE_LEVELS:
    for steering in ACTION_STEERING_LEVELS:
        DISCRETE_ACTIONS.append({
            "throttle": throttle,
            "steering": steering,
            "brake": 0.0,
        })

for steering in ACTION_STEERING_LEVELS:
    DISCRETE_ACTIONS.append({
        "throttle": 0.0,
        "steering": steering,
        "brake": 1.0,
    })

ACTION_NAMES = {
    idx: (
        f"T={action['throttle']:.1f}, "
        f"S={action['steering']:.1f}, "
        f"B={action['brake']:.1f}"
    )
    for idx, action in enumerate(DISCRETE_ACTIONS)
}
ACTION_STAND = next(
    idx
    for idx, action in enumerate(DISCRETE_ACTIONS)
    if action["throttle"] == 0.0
    and action["steering"] == 0.0
    and action["brake"] == 0.0
)

# Pygame window and drawing settings
WINDOW_SIZE = 1000
FPS = 30
MAP_RECT = (0, 0, WINDOW_SIZE, WINDOW_SIZE)
PYGAME_FONT_SIZE = 24
ROBOT_DIRECTION_LINE_LENGTH = 0.03
MAP_BORDER_WIDTH = 3
RAY_LINE_WIDTH = 2
ROBOT_DIRECTION_LINE_WIDTH = 5

ROBOT_NAVIGATION_CAPTION = "Robot Navigation"
DQN_AGENT_VISUALIZATION_CAPTION = "DQN Agent Visualization"

# Shared colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
GRAY = (128, 128, 128)

# Status labels
STATUS_SUCCESS = "SUCCESS!"
STATUS_CRASHED = "CRASHED!"
STATUS_RUNNING = "Running"

# Manual visualization text positions
VISUALIZE_REWARD_TEXT_POS = (10, 10)
VISUALIZE_STEPS_TEXT_POS = (10, 40)
VISUALIZE_DISTANCE_TEXT_POS = (10, 70)
VISUALIZE_STATUS_TEXT_POS = (10, 100)
VISUALIZE_ROBOT_TEXT_POS = (10, 130)

# Agent visualization text positions and runtime settings
VISUALIZE_MODEL_FILENAME = "4_obstacles/last_v5.1.pth"
VISUALIZE_AGENT_EPISODE_TEXT_POS = (10, 10)
VISUALIZE_AGENT_STEP_TEXT_POS = (10, 40)
VISUALIZE_AGENT_REWARD_TEXT_POS = (10, 70)
VISUALIZE_AGENT_EPISODE_REWARD_TEXT_POS = (10, 100)
VISUALIZE_AGENT_ACTION_TEXT_POS = (10, 130)
VISUALIZE_AGENT_DISTANCE_TEXT_POS = (10, 160)
VISUALIZE_AGENT_STATUS_TEXT_POS = (10, 190)
VISUALIZE_AGENT_ROBOT_TEXT_POS = (10, 220)
VISUALIZE_AGENT_EPSILON = 0.1