# Random generation and ray-casting settings
RAYS_AMOUNT_GENERATION = 8
MIN_FROM_ROBOT_TO_TARGET_DIST_GENERATION = 0.2
MIN_FROM_ROBOT_TO_OBS_DIST_GENERATION = 0.05
MIN_OBS_RADIUS_GENERATION = 0.04
MAX_OBS_RADIUS_GENERATION = 0.07
MAX_ATTEMPTS_FOR_WHILE_GENERATION = 1000
MIN_FROM_OBS_TO_OBS_DIST_GENERATION = 0.01
MIN_FROM_OBS_TO_TARGET_DIST_GENERATION = 0.03
MAP_EDGES_BUFFER_DURING_GENERATION = 0.01

# Episode termination thresholds and ray normalization
FROM_ROBOT_TO_TARGET_DIST_ACCURACY_REGISTRATION = 0.04
FROM_ROBOT_TO_OBS_DIST_ACCURACY_REGISTRATION = 0.001
FROM_ROBOT_TO_EDGES_DIST_ACCURACY_REGISTRATION = 0.001
RAY_MAX_DIST = 2**0.5

# RobotEnv runtime configuration
ENV_STEP_SIZE = 0.01
ENV_TURN_ANGLE = 0.1
EPISODE_MAX_STEPS = 200
ENV_NUM_OBSTACLES = 8
ENV_ROBOT_RADIUS = 0.02
ENV_TARGET_RADIUS = 0.03

# Reward shaping constants
DENSE_REWARD_COEFF = 30
TIME_PENALTY = 2
LARGE_REWARD = 1000
LARGE_PENALTY = 100

# Training loop hyperparameters
TRAIN_NUM_EPISODES = 5000
TRAIN_AGENT_HIDDEN_SIZE = 128
TRAIN_LEARNING_RATE = 0.0005
TRAIN_GAMMA = 0.95
TRAIN_BUFFER_SIZE = 50000
TRAIN_BATCH_SIZE = 128
TRAIN_TARGET_UPDATE = 700
TRAIN_MAX_GRAD_NORM = 10.0
TRAIN_EPSILON = 1.0
TRAIN_EPSILON_MIN = 0.01
TRAIN_EPSILON_DECAY = 0.9995

# Output paths and filenames
MODEL_DIR = "models"
BEST_DQN_MODEL_FILENAME = "best_dqn_model.pth"
TRAINING_RESULTS_FILENAME = "training_results.png"

# Training progress and plot settings
TRAINING_PROGRESS_DESC = "Training"
TRAINING_PLOT_FIGSIZE = (12, 10)
TRAINING_PLOT_REWARD_SUBPLOT = (2, 2, 1)
TRAINING_PLOT_LOSS_SUBPLOT = (2, 2, 2)
TRAINING_PLOT_EPSILON_SUBPLOT = (2, 2, 3)
TRAINING_PLOT_LENGTH_SUBPLOT = (2, 2, 4)
TRAINING_PLOT_REWARD_COLOR = "blue"
TRAINING_PLOT_LOSS_COLOR = "orange"
TRAINING_PLOT_EPSILON_COLOR = "red"
TRAINING_PLOT_LENGTH_COLOR = "green"
TRAINING_PLOT_REWARD_TITLE = "Reward History"
TRAINING_PLOT_LOSS_TITLE = "Loss History"
TRAINING_PLOT_EPSILON_TITLE = "Epsilon History"
TRAINING_PLOT_LENGTH_TITLE = "Episode Length History"
TRAINING_PLOT_EPISODE_LABEL = "Episode"
TRAINING_PLOT_REWARD_LABEL = "Reward"
TRAINING_PLOT_LOSS_LABEL = "Loss"
TRAINING_PLOT_EPSILON_LABEL = "Epsilon"
TRAINING_PLOT_LENGTH_LABEL = "Episode Length"

# Discrete action ids and display names
ACTION_STAND = 0
ACTION_FORWARD = 1
ACTION_BACKWARD = 2
ACTION_LEFT = 3
ACTION_RIGHT = 4
ACTION_NAMES = {
    ACTION_STAND: "Stand",
    ACTION_FORWARD: "Forward",
    ACTION_BACKWARD: "Backward",
    ACTION_LEFT: "Left",
    ACTION_RIGHT: "Right",
}
ACTION_UNKNOWN_NAME = "Unknown"

# Pygame window and drawing settings
WINDOW_SIZE = 1000
FPS = 30
MAP_RECT = (0, 0, WINDOW_SIZE, WINDOW_SIZE)
PYGAME_COORD_MAX = 1.0
PYGAME_FONT_SIZE = 24
ROBOT_DIRECTION_LINE_LENGTH = 0.03
MAP_BORDER_WIDTH = 3
RAY_LINE_WIDTH = 2
ROBOT_DIRECTION_LINE_WIDTH = 5
RAY_COLOR_MAX = 255

ROBOT_NAVIGATION_CAPTION = "Robot Navigation"
DQN_AGENT_VISUALIZATION_CAPTION = "DQN Agent Visualization"

# Shared colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
GRAY = (128, 128, 128)

# Status labels
STATUS_SUCCESS = "SUCCESS!"
STATUS_CRASHED = "CRASHED!"
STATUS_RUNNING = "Running"

# Manual visualization text positions
VISUALIZE_REWARD_TEXT_POS = (10, 10)
VISUALIZE_STEPS_TEXT_POS = (10, 40)
VISUALIZE_DISTANCE_TEXT_POS = (10, 70)
VISUALIZE_STATUS_TEXT_POS = (10, 100)
VISUALIZE_ROBOT_TEXT_POS = (10, 130)

# Agent visualization text positions and runtime settings
VISUALIZE_AGENT_EPISODE_TEXT_POS = (10, 10)
VISUALIZE_AGENT_STEP_TEXT_POS = (10, 40)
VISUALIZE_AGENT_REWARD_TEXT_POS = (10, 70)
VISUALIZE_AGENT_EPISODE_REWARD_TEXT_POS = (10, 100)
VISUALIZE_AGENT_ACTION_TEXT_POS = (10, 130)
VISUALIZE_AGENT_DISTANCE_TEXT_POS = (10, 160)
VISUALIZE_AGENT_STATUS_TEXT_POS = (10, 190)
VISUALIZE_AGENT_ROBOT_TEXT_POS = (10, 220)
VISUALIZE_AGENT_EPSILON = 0.0